### ISSUE TITLE
Slow performance when window is bigger.

### ISSUE THREAD

**Issue by trusktr** [extr0py/oni#93] opened 2016-12-14 00:47 UTC
If I go full-screen on a vertical monitor (a monitor rotated 90 degrees so that it shows as many lines of code as is can when oni-vim is full screen), then the rendering speed slows down drastically when scrolling (f.e. by holding down `ctrl+y`). I hope the performance can be improved, I think this project is promising!

However, with small screens, it seems to be soother than vanilla terminal Neovim.

**Comment by bert88sta** [comment] 2016-12-14 03:53
Trust me, this is a thing we're working on. By "we" I mean @extr0py because I don't know what I'm doing besides a bugfix here and there. 

Thanks for bringing this up, any other testing bugs or issues would be welcome!

-- Bret

**Comment by extr0py** [comment] 2016-12-14 14:17
Thanks for the report, @trusktr ! Seems related to #88 

Luckily I believe there is a lot of room for improvement here - the strategy the current `CanvasRenderer` is using is really naive and is essentially a prototype. It's promising that in a smaller window it's on par with terminal VIM... means that there should be no fundamental blockers to achieving that in a larger window too.

I'll close this out as a duplicate of #88, since I'll start adding some ideas for discussion there. If you feel like this might be different or unrelated, feel free to re-open. Thanks for trying it out!

**Closed by extr0py** 2016-12-14 14:17 UTC
Labels: duplicate, performance
