### ISSUE TITLE
Cannot open new window/buffer with Oni > New once all windows have closed

### ISSUE THREAD

**Issue by daenney** [extr0py/oni#660] opened 2017-08-25 08:42 UTC
Environment: macOS High Sierra
Oni: 0.2.8

Steps to reproduce:

- Launch an Oni instance
- `:q` any buffers so the window UI disappears
- Try any of the following options in tho Oni/File menu
  - New
  - Close
  - Preferences > Edit
  - Save
  - Save As
  - Save all

Note: I cannot reproduce this without `:q` as the UI won't let me close the last buffer.

Result:
<img width="532" alt="screen shot 2017-08-25 at 10 36 19" src="https://user-images.githubusercontent.com/569574/29706398-0acbaaee-8982-11e7-8723-3ca2ee844b7e.png">

**Comment by extr0py** [comment] 2017-08-25 14:11
Thanks for logging the issue @daenney ! This looks like a duplicate of #484 - we need to handle the case on OSX where the menu is open but there is no `BrowserWindow` available. I'll close for now as a duplicate, but feel free to reopen if #484 isn't sufficiently tracking this.

**Closed by extr0py** 2017-08-25 14:11 UTC
Labels: duplicate
