### ISSUE TITLE
[Bug] Javascript error after opening config.js

### ISSUE THREAD

**Issue by neilcode** [extr0py/oni#639] opened 2017-08-22 02:34 UTC
After opening config.js via the menu at Oni => Preferences => Edit Oni config

If the user executes `:q!` to exit without changes and then attempts Oni => New, the following error occurs:
![screen shot 2017-08-21 at 7 28 21 pm](https://user-images.githubusercontent.com/7885337/29546196-b3474102-86a7-11e7-8df9-23b06c18b350.png)

**Comment by extr0py** [comment] 2017-08-22 14:48
Thanks for logging the issue, @neilcode ! (And for the screenshot)

Looks like this is a duplicate of #484 - if there isn't an active 'Oni Window', the menu options will fail. I'll use #484 to track and add the 'duplicate' tag here.

**Closed** 2017-08-22 14:48 UTC
Labels: bug, duplicate
