### ISSUE TITLE
Rendering of Airline/Powerline fonts

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#23] opened 2016-12-04 19:22 UTC
I use Airline, and also usually have a zsh terminal hidden somewhere in my buffers.

Airline looks like this:
![screen shot 2016-12-04 at 2 21 33 pm](https://cloud.githubusercontent.com/assets/8421641/20868582/fb8a7e40-ba2c-11e6-9c6b-3889a9ebee56.png)

The terminal similarly does not render the patched fonts correctly, and I set and resourced guifonts to a powerline font in my init.vim.

If this is something stupid that I'm forgetting, it probably should go into a "getting started" somewhere.

I really want to see this project take off!

**Comment by extr0py** [comment] 2016-12-04 19:47
Ah yes, I haven't tested with any patched fonts. Thanks for the screenshot, that's really helpful.

Right now, Oni doesn't check 'guifont', and renders based on a config setting in (Config.ts)[https://github.com/extr0py/oni/blob/master/browser/src/Config.ts]:
```
const MacConfig: any = {
    "editor.fontFamily": "Monaco"
}

const WindowsConfig: any = {
    "editor.fontFamily": "Consolas"
}
```

You could try editing this directly here to reflect your patched powerline font, and see if that works. 

This value also gets ready in the ~/.oni/config.json, so you could add a config.json there that looks like:
```
{
"editor.fontFamily": "Patched Powerline Fontname"
}
```

Let me know if that works. Will add notes about this in the README - need to add some info about the non-standard configuration for these options.

Thanks for the feedback and for trying out the app!

**Comment by bert88sta** [comment] 2016-12-04 19:49
Yep, I'll probably be using this for as far as development goes, I'm already super impressed with everything you've done so far.

**Comment by bert88sta** [comment] 2016-12-04 19:52
@extr0py for regular vim-functionality bugs, would you want an issue per or would you rather a large issue/tag that people can post in?

**Comment by extr0py** [comment] 2016-12-04 19:57
Awesome :) 

Regarding the bugs - separate issues would be ideal, since they might have different root causes.  Large issues can be tough to close! Worst case we can always split them up, too, though.

**Comment by bert88sta** [comment] 2016-12-04 20:18
@extr0py : 

I've changed in my config.json the lines you suggested to a powerline font, and the airline segments look identical. I've changed it to my other favorite colorscheme, wombat, which works just fine. Regular solarized looks really weird in gui, truecolor looks fine though.

**Comment by extr0py** [comment] 2016-12-05 14:32
Ah ok, seems like a potential issue with how the patched fonts are rendered in the app then. Patched fonts were always a pain for me even in normal VIM :)

For the statusline, I'm hoping to be able to move away from patched fonts. There's some really exciting UI work happening in the [External UI RFC](https://github.com/neovim/neovim/pull/5686) that I'd like to take advantage of in order to enable rich status lines, on par with something like Atom, without needing a patched font.  Even just having CSS styling plus font-awesome icons would give us a much improved look & feel.

If someone would be up for investigating the patched font rendering, the code in `CanvasRenderer.ts` would be a good place to start - it'd be interesting to know how the special font characters are being rendered there.

**Comment by bert88sta** [comment] 2016-12-10 21:11
After some more digging, I'm sure it's got to be some sort of incongruency between how neovim would render the fonts normally and how it's sending them to oni. I think this is this way because my terminal is zsh and uses patched fonts, which render fine. However, airline still does not. Honestly though, patched fonts are much much more relevant in the context of people using this as a terminal, since we could probably replace the statusline

**Comment by bert88sta** [comment] 2016-12-22 19:14
It works now with the loading go init.vim, I would suggest closing

**Comment by bert88sta** [comment] 2016-12-22 19:16
If you read my last comment, that was a lie. It does, however, actually recognize the glyphs, leading me to think that changing the font to a power line one would work.

**Comment by bert88sta** [comment] 2016-12-22 19:20
Alright, this is the current state of airline (granted we're hoping for separation of ui elements)  
![screen shot 2016-12-22 at 2 18 44 pm](https://cloud.githubusercontent.com/assets/8421641/21437413/ad79bc42-c851-11e6-8d2f-9cbe7b0eaf41.png)

You can see that it at least acknowledges the glyph of the patched font. Changing the font doesn't help, be it guifont in my init.vim or editor.fontfamily in config.json

**Comment by kybaeus** [comment] 2017-01-02 20:44
@bert88sta Try with the latest version of Oni.

**Comment by bert88sta** [comment] 2017-01-03 08:23
@kybaeus it works!

**Comment by extr0py** [comment] 2017-01-03 16:01
Sweeet! Thanks @kybaeus ! I'll close this out

**Comment by keforbes** [comment] 2017-01-04 17:30
If airline is now working in Oni, how do you guys feel about adding it as one of the default plugins included with Oni?  It's a pretty popular plugin and I think it would help make Oni look more like an IDE and less like a simple text editor.  Just a suggestion. 😄

**Comment by extr0py** [comment] 2017-04-05 15:12
Looks like this issue is resolved, and #201 is tracking an external statusline implementation, which should help making Oni look like a real IDE :smile:

**Closed by extr0py** 2017-04-05 15:12 UTC
Labels: bug, difficulty:medium, help wanted

**Comment by icearith** [comment] 2018-04-10 11:08
@bryphe how to solve this rending problem?

<img width="614" alt="screen shot 2018-04-10 at 7 07 32 pm" src="https://user-images.githubusercontent.com/2555093/38553680-88dbfe06-3cf2-11e8-9314-b660b0cd83e2.png">

**Comment by zhaogang92** [comment] 2019-02-07 06:25
@icearith same rendering issue here. How did you solve it?
