### ISSUE TITLE
"Open Folder" and "Open File" without an open window throws exception

### ISSUE THREAD

**Issue by DeMuu** [extr0py/oni#693] opened 2017-09-05 06:03 UTC
Hey,

I'm not sure if this is a known issue as I didn't find anything about it yet. I just installed version 0.2.8 on macOS Sierra 10.12.6 and stumbled upon this error.

![image](https://user-images.githubusercontent.com/19406963/30047234-53546594-9210-11e7-81a6-79a4c8837aed.png)

When Oni is launched but all the window instances are closed and I try to open a folder it shows the exception from the screenshot above.

And when trying to just open a file, the dialog comes up at first but if I decide to cancel, yet another exception is thrown (see below).

![image](https://user-images.githubusercontent.com/19406963/30047291-a575a0f4-9210-11e7-91c0-66134e74ac3a.png)

**Comment by extr0py** [comment] 2017-09-07 14:55
Thanks for logging the issue and the screenshots, @DeMuu ! Looks like this is a duplicate of #484 - we need to handle the case where there are no 'oni' windows open and a menu option is accessed.

Will close this as a duplicate of #484, but feel free to reopen if that isn't adequately tracking the issue.

**Closed** 2017-09-07 14:55 UTC
Labels: crash, daily-editor-blocker, duplicate, mac
