### ISSUE TITLE
Execute oni directly from terminal

### ISSUE THREAD

**Issue by Kcrong** [extr0py/oni#668] opened 2017-08-28 03:10 UTC
Hi, I just installed `oni` with [THIS](https://github.com/extr0py/oni#mac) method, 
but I couldn't find how to execute oni directly.

It seems kind of plugin with neovim, but I still have same design of vim. 

so question. how can I run a oni directly from the terminal

I'm using OS X

**Comment by extr0py** [comment] 2017-08-28 03:56
Hi @Kcrong ,

Thanks for trying out Oni! Yes, we're actually just working on finalizing this. There has been a PR in #646 that adds a helper to 'Add to Path' on OSX.  #636 is also tracking the remaining work, basically a shell script we can use to start Oni.

Probably the simplest way to get Oni in your path is to [build from source](https://github.com/extr0py/oni#build), as the `npm link` command will expose a global `oni` shell command. Hope that helps!

It will be really nice to have this streamlined on OSX with the fix for #646 and the fix for #636 in.

I'll close this as a duplicate of #636, but let me know if you have any further questions.

**Comment by Kcrong** [comment] 2017-08-28 04:11
@extr0py Thanks you for response!

I have one more question.
If I use [command-palette](https://github.com/extr0py/oni#command-palette), 
it just show me `Loading ...` Like:
![image](https://user-images.githubusercontent.com/13450715/29758912-53fd20ea-8bf2-11e7-896f-f71cc96ccb05.png)

I entered command palette with `Ctrl + p`.

**Comment by extr0py** [comment] 2017-08-28 04:23
Sure thing! That looks like a duplicate of #662 - we don't do a very good job at the moment of handling the case where you open the fuzzy finder from home or a root dir. 

If you follow the workaround mentioned there, and select a folder, like `Ctrl+Shift+P` -> `Open Folder`. You can also just use the vim command like `:cd /my/folder`. At that point, once a folder is opened, the fuzzy finder should work better. Hope that helps!

**Comment by Kcrong** [comment] 2017-08-28 04:38
Thanks! it works very well :)
Also, it is really cool

**Comment by Kcrong** [comment] 2017-08-28 06:53
@extr0py FYI, you can close this issue :)

**Comment by extr0py** [comment] 2017-08-28 14:06
Sweet, thanks @Kcrong , glad that worked for now 👍  Thanks for the kind words!

**Closed by extr0py** 2017-08-28 14:06 UTC
Labels: duplicate, mac, question
