### ISSUE TITLE
Finder window closes immediately after selecting Open Folder with Fuzzy Finder

### ISSUE THREAD

**Issue by someguynamedmatt** [extr0py/oni#663] opened 2017-08-26 00:45 UTC
I found this when messing with [#662](https://github.com/extr0py/oni/issues/662)...

Release: `0.2.8`
OS: Mac Sierra: 10.12.5

Steps to recreate: 
> assuming issue [#662](https://github.com/extr0py/oni/issues/662) applies to the user
* select directory button (?) in lower-left corner of Oni window
* select home directory (i.e. `/Users/me` or `~/me`), click `Open`
> home directory should be visible in the lower-left now
![screen shot 2017-08-25 at 5 42 50 pm](https://user-images.githubusercontent.com/17413539/29737065-daf277fe-89bc-11e7-9c60-5b7619ca38cb.png)
* open fuzzy finder `<C-P>`
* select `Open Folder` (`<C-n>` then `Enter`)

Now the finder will open up and immediately close. I'm unsure if this and [#662](https://github.com/extr0py/oni/issues/662) are related.

**Comment by cyansprite** [comment] 2017-08-28 04:44
Would love to help but unfortunately I don't have a Mac and Linux and Windows works perfect for me.
Does this happen when opening a folder from the menu as well? I think I used the same exact logic with QuickOpen.

**Comment by extr0py** [comment] 2017-08-28 04:46
Interesting, thanks for logging the issue, @someguynamedmatt ! I'm able to reproduce this too with the step you provided. Very helpful, it was interesting to note the different experiences between clicking the path vs 'Open Folder'.

I also noticed that, in the Command Palette (`<C-S-P>`) _clicking_ on the 'Open Folder' option directly works, but pressing enter fails as you describe. I'm suspecting that the 'enter' key is actually picked up by OSX's Open File/Folder dialog, and dismisses it immediately. Going to test that out and see if that's the issue...

**Comment by extr0py** [comment] 2017-08-28 04:47
> Would love to help but unfortunately I don't have a Mac and Linux and Windows works perfect for me.

Ah ya, unfortunately this looks a quirk specific to Mac - appreciate the offer though!

**Comment by someguynamedmatt** [comment] 2017-09-01 04:21
@extr0py What files should I check out to see where this issue might be coming from?

**Comment by extr0py** [comment] 2017-09-01 16:40
Hmm, I haven't been able to dig into this too much - but I suspect what's happening here is that we OSX's platform open-folder modal on the _keydown_ event, and that experience actually listens for a _keyup_ event!

A few options here:
- A quick-and-dirty option to validate this is the issue would be to switch the event we listen to from "keydown" to "keyup" - this happens in `Keyboard.ts". This wouldn't be a viable long-term solution, because it would hurt the typing latency when editing, but it could help us at least validate the hypothesis.
- A longer-term fix, if that is the issue, would be to delay showing the open folder until we receive a 'keyup' event - the open folder action is registered in `Commands.ts`, so we could add some logic there to hold off on opening it until we have a `keyup` event.
- An alternative long-term fix,  would be to have some category of commands that we listen to on `keyup`, and have open folder be one of those commands.

There might be another possibility, like hook the `keyup` event in `Keyboard.ts`, and always prevent default/stoppropagation for the enter key in that case.

Hope that helps gives some ideas, at least! Thanks for your help with this :smile:

**Comment by extr0py** [comment] 2017-09-02 19:02
This was fixed by PR #681 . Thanks for the help and fix, @someguynamedmatt !

**Closed by extr0py** 2017-09-02 19:02 UTC
Labels: bug, help wanted, mac
