### ISSUE TITLE
Implement friendlier error message (and runtime check) for wrong Neovim version (not Error: 0,Invalid method name)

### ISSUE THREAD

**Issue by v3ss0n** [extr0py/oni#191] opened 2017-02-02 18:36 UTC
Just spitting out `Error: 0,Invalid method name` and not working

**Comment by v3ss0n** [comment] 2017-02-02 18:49
Node  6.2.1 
Os Linux Sabayon (gentoo Variant)

Build is success but fails at startup.

**Comment by extr0py** [comment] 2017-02-03 15:10
Thanks @v3ss0n for the report. 

A few questions:
1) Was this installed via `npm install -g oni-vim` or git cloned and then `npm install` / `npm run build`? It sounds like the latter but wanted to check
2) Do you have a screenshot of the error?
3) Is the error in the terminal, or does ONI start and then show the error in an alert?

**Comment by v3ss0n** [comment] 2017-02-03 15:52
- tried both , i got that error on both NPM install and Git.
- I will take screenshot later on mobile now. Basically just blank Electron shell , with menus and that error.
- No , an alert dialog.

**Comment by extr0py** [comment] 2017-02-04 15:11
Interesting, thanks for the update. That helps to know it is when the app has started and created the window.

After you dismiss the alert, can you try the following:
1) Open up the Developer Tools (from the command menu)
2) Type 'window.location.reload()' in the developer console

The error should pop up there with a callstack - that would help significantly in troubleshooting. 

I'm wondering also if it is related to how we look for config files - maybe the directory we are looking for the config files is not correct on that Linux distro.

**Comment by v3ss0n** [comment] 2017-02-04 18:53
ok  i will test it out later.

**Comment by bert88sta** [comment] 2017-02-14 12:48
@v3ss0n : Have you found anything more for this issue for us to work with?

**Comment by v3ss0n** [comment] 2017-02-14 22:29
```
NevoimInstance: Neovim started
bundle.js:1033 Attach success
bundle.js:26695 cross-browser-ipc: {"meta":{"destinationId":1,"originEvent":null,"senderId":8},"payload":{"command":"npm run build"},"type":"execute-shell-command"}
```
No other errors .

**Comment by extr0py** [comment] 2017-02-14 23:05
Interesting... One more question: What Neovim version are you running? We don't do a version check at the moment, so it's possible it's the wrong API version.

You can check with:
`nvim --version`

Thanks for the update!

**Comment by v3ss0n** [comment] 2017-02-14 23:46
```
nvim --version
NVIM 0.1.4
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -march=x86-64 -pipe -Wno-error -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/var/tmp/portage/app-editors/neovim-0.1.4/work/neovim-0.1.4_build/config -I/var/tmp/portage/app-editors/neovim-0.1.4/work/neovim-0.1.4/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.1.4/work/neovim-0.1.4_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.1.4/work/neovim-0.1.4_build/include
Compiled by portage@andromeda.sabayon.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

**Comment by extr0py** [comment] 2017-02-15 13:34
Cool, that helps! Oni needs Neovim *0.1.6* for the API updates - so I believe that may be the issue.

However, Oni should tell you that in a better way instead of some obscure error box. We should have the following:
- A _Prerequisites_ section for installation, calling this out
- A runtime check, with a friendlier / more actionable error message

I'm going to update this title to track these issues.

In the meantime, if you are up for [upgrading to Neovim 0.1.6](https://github.com/neovim/neovim/wiki/Installing-Neovim), try out Oni again on top of Neovim 0.1.6 and let us know if it works.

Thanks for your help troubleshooting this!

**Comment by justinmk** [comment] 2017-02-15 13:42
Note that since 0.1.7, [nvim provides](https://github.com/neovim/neovim/pull/5535) a `version` dict in the `api_info()` result, it contains various fields that help to dynamically determine compatibility. Also each function description in `api_info()` has a `since` field which indicates the `api_level` where that function first became availab.e

The fields are briefly described at `:h api-metadata`.


```
   api_info()['version'] => {
      major: 0,
      minor: 1,
      patch: 6,
      api_level: 1,
      api_compatible: 0,
      api_prerelease: false,
    }
```

**Comment by extr0py** [comment] 2017-02-15 13:44
Nice! Thanks @justinmk . That will make it easy for us to check the capabilities without a hard dependency on the neovim version.

**Comment by v3ss0n** [comment] 2017-02-15 21:42
thank you i will update nvim and test

**Comment by v3ss0n** [comment] 2017-02-16 12:28
Tested using latest nvim stable , working well , thanks a lot!

**Comment by keforbes** [comment] 2017-03-07 20:29
I believe we can close this now that #258 has been merged in.

**Comment by extr0py** [comment] 2017-03-07 20:36
Thanks for the fix & validation! Closing-

**Closed by extr0py** 2017-03-07 20:36 UTC
Labels: bug, help wanted

**Comment by extr0py** [comment] 2017-03-10 16:51
Looks like there might be a regression from this: #287
