### ISSUE TITLE
Ctrl-P error ENOENT

### ISSUE THREAD

**Issue by nzinov** [extr0py/oni#267] opened 2017-03-03 07:52 UTC
When I try to push ctrl-p I get a pop-up with this error:
`Error: Error: ENOENT: no such file or directory, stat '/home/nikolay/.config/chromium/SingletonCookie`
and nothing else happens.

**Comment by keforbes** [comment] 2017-03-03 15:04
This is a duplicate of #177 and #125.  I was actually going to spend some time with this defect today to see if I can do something about it.

**Closed** 2017-03-04 18:41 UTC
Labels: bug, duplicate, help wanted
